#ifndef PORTS_H
#define PORTS_H

// bad ports: 19, 15

#define TOP_LEFT_MOTOR -7
#define TOP_RIGHT_MOTOR 10

#define BOTTOM_LEFT_MOTOR -8
#define BOTTOM_RIGHT_MOTOR 9

#define FLYWHEEL_MOTOR 16
#define INDEXER_MOTOR -17

#define INTAKE_MOTOR_1 -3
#define INTAKE_MOTOR_2 4

#define RIGHT_TRACKING_WHEEL_TOP 'C'
#define RIGHT_TRACKING_WHEEL_BOTTOM 'D'

#define MID_TRACKING_WHEEL_TOP 'F'
#define MID_TRACKING_WHEEL_BOTTOM 'E'

#define PNEUM_SWITCHER 'A'

#define IMU_PORT 6

#endif
